spring:
#  redis:
#    host: r-2ze3cf1d25888944.redis.rds.aliyuncs.com
#    port: 6379
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: Ws2025@.
    #    url: jdbc:mysql://117.50.98.242:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
  application:
    name: DemoApplication
#  cloud:
#    nacos:
#      config:
#        server-addr: https://nacos-test.91hiwork.com
#        namespace: e2e06345-8a08-4727-bcc0-26aa1c9323c3
server:
  port: 8088


mybatis:
# type-aliases-package: com.nice.mapper
  mapper-locations: classpath:mapper/*Mapper.xml




